### ISSUE TITLE
Add measures to assure/ confirm agreement between Muver and Helper

### ISSUE THREAD

**Issue by vpio** [danielrsilver/muver#17]
# User Story

As a Muver or Helper
When I connect with another user
I would like to have some level of assurance that the agreement will be valid
So that I am properly compensated for my time/ so that my helper does not flake on me.

**Comment by danielrsilver** [comment]
We implemented posts on each listing.  Now we just need to add the ability for the Mover to approve the Helper

**Comment by danielrsilver** [comment]
When the Mover approves the Helper(s) it should not allow others to sign up anymore.
